#Creating a single Neuron

In [14]:
import pandas as pd
import numpy as np

In [ ]:
# creating three neuron
inputs = [2,3,4,5]
weights = [[0.1,0.2,0.3,0.4],
           [0.2,0.3,0.4,0.5],
           [0.3,0.4,0.5,0.6]]
bais = [-5,6,2]
layer_outputs = []
for neuron_weights, neuron_bais in zip(weights,bais):
    neuron_output = []
    for neuron_output = 0
        



In [ ]:
inputs = [2,3,4,5]
weights = [[0.1,0.2,0.3,0.4],
           [0.2,0.3,0.4,0.5],
           [0.3,0.4,0.5,0.6]]
bais = [-5,6,2]

# apply RelU activation function
layer_outputs = np.maximum(0, output)


NameError: name 'output' is not defined

In [16]:
#Creating a single Neuron
inputs=[1.3, 2.4 , 3.6, -1.8]
weights=[0.2, 0.8, -0.5, 0.3]
bias=2

output=(inputs[0]*weights[0]+
        inputs[1]*weights[1]+
        inputs[2]*weights[2]+
        inputs[3]*weights[3]+bias)

print(output)

#Apply RELU Activation Function
output=max(0,output)
print(output)


inputs = [1.3, 2.4, 3.6, -1.8]
weights1 = [0.2, 0.8, -0.5, 0.3]
weights2 = [0.5, -0.84, 0.53, -0.3]
weights3 = [-0.21, -0.62, 0.16, 0.78]

bias1 = 2
bias2 = 4
bias3 = 0.8

output =[inputs[0]*weights1[0]+
         inputs[1]*weights1[1]+
         inputs[2]*weights1[2]+
         inputs[3]*weights1[3] + bias1,

        # Neuron 2
         inputs[0]*weights1[0]+
         inputs[1]*weights1[1]+
         inputs[2]*weights1[2]+
         inputs[3]*weights1[3] + bias2,

        # Neuron 3
         inputs[0]*weights1[0]+
         inputs[1]*weights1[1]+
         inputs[2]*weights1[2]+
         inputs[3]*weights1[3] + bias3]

print(output)

# Creating 3 Neurons
inputs = [1.3, 2.4, 3.6, -1.8]
weights = [
    [0.2, 0.8, -0.5, 0.3],
    [0.5, -0.84, 0.53, -0.3],
    [-0.21, -0.62, 0.16, 0.78],
]
bias = [2, 4, 0.8]

# Compute each neuron output using the weight matrix
output = [
    inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + inputs[2] * weights[0][2] + inputs[3] * weights[0][3] + bias[0],
    inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + inputs[2] * weights[1][2] + inputs[3] * weights[1][3] + bias[1],
    inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + inputs[2] * weights[2][2] + inputs[3] * weights[2][3] + bias[2],
]

print(output)

inputs = [2, 3, 4, 5]
weights = [[0.1, 0.2, 0.3, 0.4],
           [0.2, 0.3, 0.4, 0.5],
           [0.3, 0.4, 0.5, 0.6]]

bias = [-5, 6, 2]

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, bias):
    neuron_output = 0

    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input * weight

    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

layer_outputs = np.maximum(0, layer_outputs)
print(layer_outputs)

inputs = [2, 3, 4, 5]
weights = [[0.1, 0.2, 0.3, 0.4],
          [0.2, 0.3, 0.4, 0.5],
          [0.3, 0.4, 0.5, 0.6]]

bias = [-5, 6, 2]
output=np.dot(weights,inputs)+bias
print(output)

inputs = [2, 3, 4, 5]
weights = [[0.1, 0.2, 0.3, 0.4],
          [0.2, 0.3, 0.4, 0.5],
          [0.3, 0.4, 0.5, 0.6],
          [0.4, 0.5, 0.6, 0.7]]

bias = [-5, 6, 2, 3]
output=np.dot(weights,inputs)+bias
print(output)

1.8399999999999996
1.8399999999999996
[1.8399999999999996, 3.84, 0.6399999999999997]
[1.8399999999999996, 5.082, -1.7890000000000004]
[ 0.  11.4  8.8]
[-1.  11.4  8.8]
[-1.  11.4  8.8 11.2]


In [17]:
# Creating a matrix with numpy dot product
inputs = np.array( [[2, 3, 4, 5],[1,2,3,4],[0,1,2,3]])
weights = np.array([[0.1, 0.2, 0.3, 0.4],
                    [0.2, 0.3, 0.4, 0.5],
                    [0.3, 0.4, 0.5, 0.6]])
bias = np.array([-5, 6, 2])
output=np.dot(weights,inputs.T)+bias
print(output)


[[-1.   9.   4. ]
 [ 0.4 10.   4.6]
 [ 1.8 11.   5.2]]


In [ ]:
# Creating a matrix with numpy dot product
inputs = np.array( [[2, 3, 4, 5],[1,2,3,4],[0,1,2,3]])
weights = np.array([[0.1, 0.2, 0.3, 0.4],
                    [0.2, 0.3, 0.4, 0.5],
                    [0.3, 0.4, 0.5, 0.6]])
bias = np.array([-5, 6, 2])
output=np.dot(weights,inputs.T)+bias
#apply RelU activation function
layer_outputs = np.maximum(0, output)
print(layer_outputs)



[[ 0.   9.   4. ]
 [ 0.4 10.   4.6]
 [ 1.8 11.   5.2]]


In [19]:
inputs = np.array( [[2, 3, 4, 5],[1,2,3,4],[0,1,2,3]])
weights = np.array([[0.1, 0.2, 0.3, 0.4],
                    [0.2, 0.3, 0.4, 0.5],
                    [0.3, 0.4, 0.5, 0.6]])
bias = np.array([-5, 6, 2])
output=np.dot(weights,inputs.T)+bias
#apply Tanh activation function
layer_outputs = np.tanh(output)
print(layer_outputs)

[[-0.76159416  0.99999997  0.9993293 ]
 [ 0.37994896  1.          0.99979794]
 [ 0.94680601  1.          0.99993914]]


In [20]:
inputs = np.array( [[2, 3, 4, 5],[1,2,3,4],[0,1,2,3]])
weights = np.array([[0.1, 0.2, 0.3, 0.4],
                    [0.2, 0.3, 0.4, 0.5],
                    [0.3, 0.4, 0.5, 0.6]])
bias = np.array([-5, 6, 2])
output=np.dot(weights,inputs.T)+bias
#apply Sigmoid activation function
layer_outputs = 1 / (1 + np.exp(-output))   
print(layer_outputs)

[[0.26894142 0.99987661 0.98201379]
 [0.59868766 0.9999546  0.9900482 ]
 [0.85814894 0.9999833  0.9945137 ]]
